version: "3.7"

services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "443:443"
      - "80:80"
    links:
      - web
      - cms
      - send

  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env.prod
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    image: neurosnap/lists-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
    links:
      - db
  cms:
    image: neurosnap/lists-cms
    restart: unless-stopped
    ports:
      - "2222:2222"
    env_file:
      - .env.prod
    links:
      - db
    volumes:
      - ssh_data:/app/ssh_data
  send:
    image: neurosnap/lists-send
    restart: unless-stopped
    ports:
      - "2223:2223"
    env_file:
      - .env.prod
    links:
      - db
    volumes:
      - ssh_data:/app/ssh_data

volumes:
  db_data:
  caddy_data:
  ssh_data:
  caddy_config:
